# Generated by Django 4.1.7 on 2023-02-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adaar',
            field=models.ImageField(default='a', upload_to=' ,null=True', verbose_name='Your Image in jpg/png Format'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birthcertif',
            field=models.ImageField(null=True, upload_to=' ', verbose_name='Your Image in jpg/png Format'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to=' ', verbose_name='Your Image in jpg/png Format'),
        ),
        migrations.AddField(
            model_name='student',
            name='sslc',
            field=models.ImageField(null=True, upload_to=' ', verbose_name='Your Image in jpg/png Format'),
        ),
    ]
