# Generated by Django 4.1.1 on 2023-03-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0002_student_adaar_student_address_student_birthcertif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='', upload_to='driving/drapp/static/img'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='driving/drapp/static/img'),
        ),
        migrations.AlterField(
            model_name='student',
            name='adaar',
            field=models.ImageField(null=True, upload_to=' ', verbose_name='Your Image in jpg/png Format'),
        ),
    ]
