# Generated by Django 4.1.1 on 2023-03-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0004_alter_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='drapp/static/img'),
        ),
    ]
