# Generated by Django 4.1.1 on 2023-03-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0005_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='', upload_to='media/instructors/'),
        ),
    ]
