# Generated by Django 4.1.1 on 2023-04-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0007_remove_student_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='nothing', max_length=20),
        ),
    ]
