# Generated by Django 4.1.1 on 2023-04-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0008_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adaar',
            field=models.ImageField(null=True, upload_to='aadar/', verbose_name='Your Image in jpg/png Format'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthcertif',
            field=models.ImageField(null=True, upload_to='certificates/', verbose_name='Your Image in jpg/png Format'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sslc',
            field=models.ImageField(null=True, upload_to='sslc/', verbose_name='Your Image in jpg/png Format'),
        ),
    ]
