# Generated by Django 4.1.1 on 2023-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0009_alter_student_adaar_alter_student_birthcertif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='nothing', max_length=20),
        ),
    ]
