# Generated by Django 4.1.1 on 2023-04-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0012_alter_slot_slottime'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(default='Not Booked', max_length=20),
        ),
    ]
