# Generated by Django 4.1.1 on 2023-04-17 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0013_slot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Not Booked', max_length=20)),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drapp.instructor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drapp.slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drapp.student')),
            ],
        ),
    ]
