# Generated by Django 4.1.1 on 2023-04-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0015_remove_bookslot_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drapp.instructor'),
        ),
    ]
