# Generated by Django 4.1.1 on 2023-04-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0016_bookslot_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='instructor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='drapp.instructor'),
        ),
    ]
