# Generated by Django 4.1.1 on 2023-05-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0019_instructor_image2_instructor_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verification Status'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.CharField(default='Not Verified', max_length=20, verbose_name='Current Status'),
        ),
    ]
